name: Retrain ML Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python (tanpa conda)
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn matplotlib seaborn

      - name: Run MLflow Project
        run: |
          cd MLProject
          echo "Running MLflow project retraining..."
          mlflow run . --env-manager=local -P data_path=housing_preprocessed.csv
