name: Retrain ML Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:   # biar bisa dijalankan manual dari tab Actions

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      # --- Step 1: Checkout repository ---
      - name: 🧩 Checkout repository
        uses: actions/checkout@v3

      # --- Step 2: Set up Miniconda ---
      - name: 🐍 Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env
          auto-update-conda: true
          use-mamba: true
          miniforge-variant: Miniforge3   # ✅ GANTI INI
          channels: conda-forge,defaults

      # --- Step 3: Debugging info awal ---
      - name: 🔍 Debug Environment Info
        run: |
          echo "=== Python & Conda Info ==="
          which python
          python --version
          conda info
          echo ""
          echo "=== Conda Environments ==="
          conda env list
          echo ""
          echo "=== Installed Packages ==="
          pip list
          echo ""
          echo "=== MLProject Folder Structure ==="
          ls -R MLProject
          echo ""
          echo "=== MLflow Version ==="
          pip show mlflow || echo "MLflow not installed"
      
      # --- Step 4: Reinstall MLflow (jaga-jaga versi) ---
      - name: ⚙️ Ensure MLflow Installed
        run: |
          echo "Reinstalling MLflow for compatibility..."
          pip install --upgrade mlflow

      # --- Step 5: Run MLflow project dengan logging detail ---
      - name: 🚀 Run MLflow Project (with detailed logging)
        run: |
          set -e  # stop kalau error
          cd MLProject
          echo "=== Start MLflow run ==="
          mlflow --version
          echo "Executing MLflow project..."
          mlflow run . -P data_path=housing_preprocessed.csv --verbose
          echo "=== MLflow run completed ==="
          cd ..

      # --- Step 6: Tambahan logging kalau error ---
      - name: 🧾 Print Conda Logs (if available)
        if: failure()
        run: |
          echo "=== Conda logs (if exist) ==="
          find /usr/share/miniconda/ -type f -name "*.log" | xargs -I {} sh -c 'echo "--- {} ---"; cat "{}"; echo ""'
          echo "=== End of Conda logs ==="
